config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :admins do
    collection do
      get 'checklogin'
    end
  end
  resources :regions do
    collection do
      get 'getnodes'
      get 'updatenodes'
      get 'shownodes'
      get 'showedit'
    end
  end
  resources :users do
    collection do
      get 'getregion'
      get 'getregionparent'
      get 'in'
      get 'getregionall'
    end
    resources :deposits do
      member do
        get 'redto'
      end
    end
    resources :takeouts do
      member do
        get 'redto'
      end
    end
    resources :cards
    resources :srelations
    resources :finterests do
      collection do
        get 'hasinterest'
        get 'nointerest'
      end
    end
  end
  resources :interestversions
  resources :deposittypedefs
  resources :relationdefs
  resources :usercounts
  resources :regioncounts do
    collection do
      get 'getuser'
    end
  end
  resources :flogs
  resources :logins do
    collection do
      get 'changebrowse'
    end
  end
  resources :settings do
    collection do
      get 'savemonthday'
    end
  end
  resources :modifypwds
  resources :depositdayreports do
    collection do
      get 'getvalue'
    end
  end
  resources :depositmonthreports do
    collection do
      get 'getvalue'
    end
  end
  resources :noauths
  resources :tests
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/capital.rb
class Capital < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :takeouts
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :deposittypedef
  belongs_to :user
end

app/models/deposittypedef.rb
class Deposittypedef < ApplicationRecord
  has_many :deposits
end

app/models/finterest.rb
class Finterest < ApplicationRecord
  belongs_to :user

  def self.interest
    users = User.all
    users.each do |user|
      10.times do |tice|
        deposits = user.deposits
        if deposits.count > 0 && deposits.last.created_at < Time.now - tice.day
          #if deposits.count > 0
          interests = user.finterests.where('interestday = ?  and interesttype = 0',(Time.now - tice.day).beginning_of_day)
          if interests.count == 0 && user.capital > 0
            rate = user.interestversion.rate * user.capital
            interests.create(amount:rate,incapitalstatus:0,interesttype:0,interestday:(Time.now - tice.day).beginning_of_day)
            Flog.create(log:'日息计息 '+user.username+':￥'+rate.to_s+' 计息版本'+((Time.now - tice.day).beginning_of_day).strftime('%Y%m%d'),logtype:0,user:'system')
          end
        end
      end
    end
  end

  def self.addinterest
    if Time.now.day == Setting.first.monthday
      users = User.all
      users.each do |user|
        interests = user.finterests.where('incapitalstatus = 0')
        if interests.count > 0
          interestsum = user.finterests.where('incapitalstatus = 0').sum('amount')
          user.capital += interestsum
          user.save
          Flog.create(log:'计入本金 '+user.username+':￥'+interestsum.to_s,logtype:0,user:'system')
          interestlogs = user.interestlogs
          interestlogs.create(amount:interestsum)
          interests.each do |interest|
            interest.incapitalstatus = 1
            interest.save
          end
        end
      end
    end
  end

end

app/models/flog.rb
class Flog < ApplicationRecord
end

app/models/interestlog.rb
class Interestlog < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :users
  has_many :childrens, class_name: "Region", foreign_key: "up_id"
  belongs_to :parent, class_name: "Region", foreign_key: "up_id",optional: true
end

app/models/relationdef.rb
class Relationdef < ApplicationRecord
  has_many :srelations
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/srelation.rb
class Srelation < ApplicationRecord
  belongs_to :relationdef
  belongs_to :user
end

app/models/takeout.rb
class Takeout < ApplicationRecord
  belongs_to :user
  belongs_to :card,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :region
  belongs_to :interestversion
  has_many :deposits
  has_many :capitals
  has_many :cards
  has_many :takeouts
  has_many :srelations
  has_many :finterests
  has_many :interestlogs
end

app/controllers/srelations_controller.rb
class SrelationsController < ApplicationController
  before_action {authen "relation"}
  before_action :set_srelation, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :new, :create, :index]
  def index
    @srelations=@user.srelations
  end

  def edit
    @relationdef=Relationdef.all
  end

  def new

    @relationdef = Relationdef.all
    @srelation = @user.srelations.new

  end

  def create
    @srelation = @user.srelations.new(srelation_params)
    @srelation.operator = session[:username]
    respond_to do |format|
      if @srelation.save
        Flog.create(log:'新增社会关系 '+@user.username+':'+@srelation.name,logtype:1,user:session[:username])
        format.html { redirect_to user_srelations_path(@user), notice: 'Unit was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @srelation.update(srelation_params)
        Flog.create(log:'编辑社会关系 '+@user.username+':'+@srelation.name,logtype:1,user:session[:username])
        format.html { redirect_to user_srelations_path(@user), notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @srelation }
      else
        format.html { render :edit }
        format.json { render json: @srelation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @srelation.destroy
    Flog.create(log:'删除社会关系 '+@user.username+':'+@srelation.name,logtype:1,user:session[:username])
    respond_to do |format|
      format.html { redirect_to user_srelations_path(@user), notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_srelation
    @srelation = Srelation.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def srelation_params
    params.require(:srelation).permit(:relationdef_id, :user_id, :name, :tel, :address, :content)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/flogs_helper.rb
module FlogsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/noauths_helper.rb
module NoauthsHelper
end

app/helpers/srelations_helper.rb
module SrelationsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/srelations/_form.html.erb
<script>
    $(document).ready(function() {
        $('#selectrelationdef').change(function () {
            $('#relationdef').val($(this).val());
        });
        if($('#relationdef').val()!=''){
            $('#selectrelationdef').val($('#relationdef').val());
        }
    });
</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for([@user,@srelation],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">名称：</label>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">关系：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :relationdef_id,class:"form-control",id:'relationdef' %>
              <select class="form-control" id="selectrelationdef">
                <option value=0>请选择关系</option>
                <% @relationdef.each do |f| %>
                    <option value=<%= f.id %> ><%= f.relation %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">地址：</label>
            <div class="col-sm-5">
              <%= f.text_field :address,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">电话：</label>
            <div class="col-sm-5">
              <%= f.text_field :tel,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">备注：</label>
            <div class="col-sm-5">
              <%= f.text_field :content,class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",user_cards_path(@user),class: "btn btn-w-m btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/srelations/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑</h3>
    </div>
    <%= render 'form', srelation: @srelation %>
  </div>
</div>
<%=render 'layerend' %>

app/views/srelations/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>关系管理</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">姓名</th>
          <th class="text-center">关系</th>
          <th class="text-center">地址</th>
          <th class="text-center">电话</th>
          <th class="text-center">经手人</th>
          <th class="text-center">备注</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @srelations.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.relationdef.relation %></td>
              <td><%= f.address %></td>
              <td><%= f.tel %></td>
              <td><%= f.operator %></td>
              <td><%= f.content %></td>

              <td>
                <%= link_to '编辑', edit_user_srelation_path(@user,f) %>
                <%= link_to '删除', [@user,f], method: :delete, data: { confirm: '确认删除?' } %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新增",new_user_srelation_path,class: "btn btn-w-m btn-primary pull-right" %>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/srelations/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增</h3>
    </div>
    <%= render 'form', srelation: @srelation %>
  </div>
</div>
<%=render 'layerend' %>