config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :admins do
    collection do
      get 'checklogin'
    end
  end
  resources :regions do
    collection do
      get 'getnodes'
      get 'updatenodes'
      get 'shownodes'
      get 'showedit'
    end
  end
  resources :users do
    collection do
      get 'getregion'
      get 'getregionparent'
      get 'in'
      get 'getregionall'
    end
    resources :deposits do
      member do
        get 'redto'
      end
    end
    resources :takeouts do
      member do
        get 'redto'
      end
    end
    resources :cards
    resources :srelations
    resources :finterests do
      collection do
        get 'hasinterest'
        get 'nointerest'
      end
    end
  end
  resources :interestversions
  resources :deposittypedefs
  resources :relationdefs
  resources :usercounts
  resources :regioncounts do
    collection do
      get 'getuser'
    end
  end
  resources :flogs
  resources :logins do
    collection do
      get 'changebrowse'
    end
  end
  resources :settings do
    collection do
      get 'savemonthday'
    end
  end
  resources :modifypwds
  resources :depositdayreports do
    collection do
      get 'getvalue'
    end
  end
  resources :depositmonthreports do
    collection do
      get 'getvalue'
    end
  end
  resources :noauths
  resources :tests
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/capital.rb
class Capital < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :takeouts
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :deposittypedef
  belongs_to :user
end

app/models/deposittypedef.rb
class Deposittypedef < ApplicationRecord
  has_many :deposits
end

app/models/finterest.rb
class Finterest < ApplicationRecord
  belongs_to :user

  def self.interest
    users = User.all
    users.each do |user|
      10.times do |tice|
        deposits = user.deposits
        if deposits.count > 0 && deposits.last.created_at < Time.now - tice.day
          #if deposits.count > 0
          interests = user.finterests.where('interestday = ?  and interesttype = 0',(Time.now - tice.day).beginning_of_day)
          if interests.count == 0 && user.capital > 0
            rate = user.interestversion.rate * user.capital
            interests.create(amount:rate,incapitalstatus:0,interesttype:0,interestday:(Time.now - tice.day).beginning_of_day)
            Flog.create(log:'日息计息 '+user.username+':￥'+rate.to_s+' 计息版本'+((Time.now - tice.day).beginning_of_day).strftime('%Y%m%d'),logtype:0,user:'system')
          end
        end
      end
    end
  end

  def self.addinterest
    if Time.now.day == Setting.first.monthday
      users = User.all
      users.each do |user|
        interests = user.finterests.where('incapitalstatus = 0')
        if interests.count > 0
          interestsum = user.finterests.where('incapitalstatus = 0').sum('amount')
          user.capital += interestsum
          user.save
          Flog.create(log:'计入本金 '+user.username+':￥'+interestsum.to_s,logtype:0,user:'system')
          interestlogs = user.interestlogs
          interestlogs.create(amount:interestsum)
          interests.each do |interest|
            interest.incapitalstatus = 1
            interest.save
          end
        end
      end
    end
  end

end

app/models/flog.rb
class Flog < ApplicationRecord
end

app/models/interestlog.rb
class Interestlog < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :users
  has_many :childrens, class_name: "Region", foreign_key: "up_id"
  belongs_to :parent, class_name: "Region", foreign_key: "up_id",optional: true
end

app/models/relationdef.rb
class Relationdef < ApplicationRecord
  has_many :srelations
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/srelation.rb
class Srelation < ApplicationRecord
  belongs_to :relationdef
  belongs_to :user
end

app/models/takeout.rb
class Takeout < ApplicationRecord
  belongs_to :user
  belongs_to :card,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :region
  belongs_to :interestversion
  has_many :deposits
  has_many :capitals
  has_many :cards
  has_many :takeouts
  has_many :srelations
  has_many :finterests
  has_many :interestlogs
end

app/controllers/takeouts_controller.rb
class TakeoutsController < ApplicationController
  before_action {authen "takeout"}
  def index
    @user = User.find(params[:user_id])
    @takeouts = @user.takeouts.order('ordernumber desc')
  end

  def new
    @user = User.find(params[:user_id])
    @cards = @user.cards
    @capital = @user.capital
  end

  def create
    @user = User.find(params[:user_id])
    @takeout = @user.takeouts.create(takeout_params)
    @takeout.operator = session[:username]
    @takeout.save
    @user.capital=@user.capital - takeout_params[:amount].to_f
    @user.save
    Flog.create(log:'新增取款 '+@user.username+':￥'+takeout_params[:amount],logtype:1,user:session[:username])
    redirect_to user_path(@user)
  end

  def redto
    @user = User.find(params[:user_id])
    takeout = Takeout.find(params[:id])
    if takeout.red.to_s == ''
      @user.capital += takeout.amount
      Flog.create(log:'红冲取款 '+@user.username+':￥'+takeout.amount.to_s,logtype:1,user:session[:username])
      Takeout.create(user_id:takeout.user_id,ordernumber:takeout.ordernumber,amount:-takeout.amount,red:1,redid:takeout.id,card_id:0)
    else
      Flog.create(log:'反冲取款 '+@user.username+':￥'+takeout.amount.to_s,logtype:1,user:session[:username])
      @user.capital += takeout.amount
      takeout.destroy
    end
    @user.save
    redirect_to user_takeouts_path(@user)
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def takeout_params
    params.require(:takeout).permit(:ordernumber,:amount, :red, :redid, :content, :card_id)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/flogs_helper.rb
module FlogsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/noauths_helper.rb
module NoauthsHelper
end

app/helpers/takeouts_helper.rb
module TakeoutsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/takeouts/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>转出记录</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">流水号</th>
          <th class="text-center">转出方式</th>
          <th class="text-center">转出金额</th>
          <th class="text-center">转出时间</th>
          <th class="text-center">操作</th>

        </tr>
        </thead>
        <tbody>
        <% @takeouts.each do |takeout| %>
            <% if takeout.red.to_s != '' %>
                <tr class="text-danger">
            <% elsif Takeout.where('ordernumber = ?',takeout.ordernumber).count > 1 %>
                <tr class="text-muted">
            <% else %>
                <tr>
            <% end %>
              <td><%= takeout.ordernumber %></td>
              <td>
                <% if takeout.card %>
                <%= takeout.card.bankdeposit %>
                    <%= takeout.card.bankaccount[0,4] %>
                    ***
                    <%= takeout.card.bankaccount[-4,4] %>
                    <% else %>
                现金
                <% end %>

              </td>
              <td><%= sprintf("%.2f",takeout.amount) %></td>
              <td><%= takeout.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
            <td>
              <% if Takeout.where('ordernumber = ?',takeout.ordernumber).count == 1 && authen('takeoutred') %>
                  <%= link_to '红冲',redto_user_takeout_path(@user,takeout) %>
              <% elsif takeout.red.to_s != '' && authen('takeoutred') %>
                  <%= link_to '反冲',redto_user_takeout_path(@user,takeout) %>
              <% end %>
            </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="text-right">
      <%= link_to "转出",new_user_takeout_path(@user),class: "btn btn-w-m btn-primary" %>&nbsp;
      <%= link_to "返回",user_path(@user),class: "btn btn-w-m btn-primary" %>
      </div>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/takeouts/new.html.erb
<%= render 'layerbegin' %>
<script>
  $(document).ready(function(){
      if($('#ordernumber').val()==''){
          var datetime = new Date();
          $('#ordernumber').val(  Format(datetime,"yyyy:MM:dd:HH:mm:ss").split(':').join(''));
      }

      $('#selectdeposittypedef').change(function(){
          $('#deposittypedefid').val($(this).val());
      });

      if($('#deposittypedefid').val()==''){
          $('#deposittypedefid').val('0');
      }

      $('#amount').keyup(function(){
          $('#amountspan').text(chineseNumber($('#amount').val()));
      });

      $('#smt').click(function(){
          debugger;
          if(parseFloat($('#amount').val())>parseFloat($('#maxamount').val())){
              $('#dangerdiv').removeClass('displaynone');
              $('#dangerdiv').addClass('display');
              return false;
          }

      });



      function Format(now,mask)
      {
          var d = now;
          var zeroize = function (value, length)
          {
              if (!length) length = 2;
              value = String(value);
              for (var i = 0, zeros = ''; i < (length - value.length); i++)
              {
                  zeros += '0';
              }
              return zeros + value;
          };

          return mask.replace(/"[^"]*"|'[^']*'|\b(?:d{1,4}|m{1,4}|yy(?:yy)?|([hHMstT])\1?|[lLZ])\b/g, function ($0)
          {
              switch ($0)
              {
                  case 'd': return d.getDate();
                  case 'dd': return zeroize(d.getDate());
                  case 'ddd': return ['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat'][d.getDay()];
                  case 'dddd': return ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][d.getDay()];
                  case 'M': return d.getMonth() + 1;
                  case 'MM': return zeroize(d.getMonth() + 1);
                  case 'MMM': return ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][d.getMonth()];
                  case 'MMMM': return ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][d.getMonth()];
                  case 'yy': return String(d.getFullYear()).substr(2);
                  case 'yyyy': return d.getFullYear();
                  case 'h': return d.getHours() % 12 || 12;
                  case 'hh': return zeroize(d.getHours() % 12 || 12);
                  case 'H': return d.getHours();
                  case 'HH': return zeroize(d.getHours());
                  case 'm': return d.getMinutes();
                  case 'mm': return zeroize(d.getMinutes());
                  case 's': return d.getSeconds();
                  case 'ss': return zeroize(d.getSeconds());
                  case 'l': return zeroize(d.getMilliseconds(), 3);
                  case 'L': var m = d.getMilliseconds();
                      if (m > 99) m = Math.round(m / 10);
                      return zeroize(m);
                  case 'tt': return d.getHours() < 12 ? 'am' : 'pm';
                  case 'TT': return d.getHours() < 12 ? 'AM' : 'PM';
                  case 'Z': return d.toUTCString().match(/[A-Z]+$/);
                  // Return quoted strings with the surrounding quotes removed
                  default: return $0.substr(1, $0.length - 2);
              }
          });
      };



  });
</script>
<style>
  .display{
      display:block;
  }
        .displaynone{
            display: none;
        }
</style>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>转出</h3>
    </div>
    <div class="col-md-12 ibox ibox-content">
      <div class="ibox-content form-horizontal m-t">
        <div class="form-group">
          <%= form_for([@user,@user.takeouts.build],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
              <div class="form-group">
                <label class="col-sm-3 control-label">流水号：</label>
                <div class="col-sm-5">
                  <%= f.text_field :ordernumber,class:"form-control",id:'ordernumber',readonly:'true' %>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-3 control-label">转出方式：</label>
                <div class="col-sm-5">
                  <%= f.hidden_field :card_id,class:"form-control",id:'deposittypedefid' %>
                  <select class="form-control" id="selectdeposittypedef">
                    <option value=0>现金</option>
                    <% @cards.each do |card| %>
                        <option value=<%= card.id %> ><%= card.bankdeposit %>&nbsp;<%= card.bankaccount %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-3 control-label">转出金额：</label>
                <div class="col-sm-5">
                  <%= f.text_field :amount,class:"form-control",id:'amount',placeholder:'最高可转出 '+@capital.to_s+" 元" %>
                  <input type="hidden" id="maxamount" value=<%= @capital %>>
                  <span id="amountspan" class="form-control text-danger"></span>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-3 control-label">备注：</label>
                <div class="col-sm-5">
                  <%= f.text_area :content,class:"form-control" %>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-3 control-label"></label>
                <div class="col-sm-5 text-right">
                  <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",users_path,class: "btn btn-w-m btn-primary " %>
                </div>
              </div>
              <div class="form-group displaynone" id="dangerdiv">
                <div class="alert alert-danger" role="alert">
                  <label class="col-sm-3 control-label"></label>
                  转出金额高于最高可转出金额
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%=render 'layerend' %>