config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :admins do
    collection do
      get 'checklogin'
    end
  end
  resources :regions do
    collection do
      get 'getnodes'
      get 'updatenodes'
      get 'shownodes'
      get 'showedit'
    end
  end
  resources :users do
    collection do
      get 'getregion'
      get 'getregionparent'
      get 'in'
      get 'getregionall'
    end
    resources :deposits do
      member do
        get 'redto'
      end
    end
    resources :takeouts do
      member do
        get 'redto'
      end
    end
    resources :cards
    resources :srelations
    resources :finterests do
      collection do
        get 'hasinterest'
        get 'nointerest'
      end
    end
  end
  resources :interestversions
  resources :deposittypedefs
  resources :relationdefs
  resources :usercounts
  resources :regioncounts do
    collection do
      get 'getuser'
    end
  end
  resources :flogs
  resources :logins do
    collection do
      get 'changebrowse'
    end
  end
  resources :settings do
    collection do
      get 'savemonthday'
    end
  end
  resources :modifypwds
  resources :depositdayreports do
    collection do
      get 'getvalue'
    end
  end
  resources :depositmonthreports do
    collection do
      get 'getvalue'
    end
  end
  resources :noauths
  resources :tests
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/capital.rb
class Capital < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :takeouts
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :deposittypedef
  belongs_to :user
end

app/models/deposittypedef.rb
class Deposittypedef < ApplicationRecord
  has_many :deposits
end

app/models/finterest.rb
class Finterest < ApplicationRecord
  belongs_to :user

  def self.interest
    users = User.all
    users.each do |user|
      10.times do |tice|
        deposits = user.deposits
        if deposits.count > 0 && deposits.last.created_at < Time.now - tice.day
          #if deposits.count > 0
          interests = user.finterests.where('interestday = ?  and interesttype = 0',(Time.now - tice.day).beginning_of_day)
          if interests.count == 0 && user.capital > 0
            rate = user.interestversion.rate * user.capital
            interests.create(amount:rate,incapitalstatus:0,interesttype:0,interestday:(Time.now - tice.day).beginning_of_day)
            Flog.create(log:'日息计息 '+user.username+':￥'+rate.to_s+' 计息版本'+((Time.now - tice.day).beginning_of_day).strftime('%Y%m%d'),logtype:0,user:'system')
          end
        end
      end
    end
  end

  def self.addinterest
    if Time.now.day == Setting.first.monthday
      users = User.all
      users.each do |user|
        interests = user.finterests.where('incapitalstatus = 0')
        if interests.count > 0
          interestsum = user.finterests.where('incapitalstatus = 0').sum('amount')
          user.capital += interestsum
          user.save
          Flog.create(log:'计入本金 '+user.username+':￥'+interestsum.to_s,logtype:0,user:'system')
          interestlogs = user.interestlogs
          interestlogs.create(amount:interestsum)
          interests.each do |interest|
            interest.incapitalstatus = 1
            interest.save
          end
        end
      end
    end
  end

end

app/models/flog.rb
class Flog < ApplicationRecord
end

app/models/interestlog.rb
class Interestlog < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :users
  has_many :childrens, class_name: "Region", foreign_key: "up_id"
  belongs_to :parent, class_name: "Region", foreign_key: "up_id",optional: true
end

app/models/relationdef.rb
class Relationdef < ApplicationRecord
  has_many :srelations
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/srelation.rb
class Srelation < ApplicationRecord
  belongs_to :relationdef
  belongs_to :user
end

app/models/takeout.rb
class Takeout < ApplicationRecord
  belongs_to :user
  belongs_to :card,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :region
  belongs_to :interestversion
  has_many :deposits
  has_many :capitals
  has_many :cards
  has_many :takeouts
  has_many :srelations
  has_many :finterests
  has_many :interestlogs
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action {authen "card"}
  def index
    @user = User.find(params[:user_id])
    @cards = @user.cards
  end

  def new
    @user = User.find(params[:user_id])
    @cards = @user.cards.new
  end

  def create
    @user = User.find(params[:user_id])
    @cards = @user.cards.new(card_params)
    @cards.operator = session[:username]
    @cards.save
    Flog.create(log:'新增银行卡 '+@user.username+':'+@cards.bankaccount,logtype:1,user:session[:username])
    redirect_to user_cards_path(@user)
  end

  def edit
    @user = User.find(params[:user_id])
    @cards=Card.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @cards=Card.find(params[:id])
    @cards.update(card_params)
    Flog.create(log:'编辑银行卡 '+@user.username+':'+@cards.bankaccount,logtype:1,user:session[:username])
    redirect_to user_cards_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @cards=Card.find(params[:id])
    Flog.create(log:'删除银行卡 '+@user.username+':'+@cards.bankaccount,logtype:1,user:session[:username])
    @cards.destroy
    redirect_to user_cards_path(@user)
  end

  private

  def card_params
    params.require(:card).permit(:name ,:bankdeposit,:bankaccount)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/flogs_helper.rb
module FlogsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/noauths_helper.rb
module NoauthsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<script>
    $(document).ready(function(){
        if($('#name').val()==''){
            $('#name').val($('#username').val());
        }
    });

</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for([@user,@cards],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">卡用户：</label>
            <div class="col-sm-5">
              <input type="hidden" id="username" value=<%=@user.username %> >
              <%= f.text_field :name,class:"form-control",id:'name' %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">开户银行：</label>
            <div class="col-sm-5">
                  <%= f.text_field :bankdeposit,class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">银行账号：</label>
            <div class="col-sm-5">
              <%= f.text_field :bankaccount,class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",user_cards_path(@user),class: "btn btn-w-m btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑银行卡</h3>
    </div>
    <%= render 'form', card: @card %>
  </div>
</div>
<%=render 'layerend' %>

app/views/cards/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>银行卡</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">卡用户</th>
          <th class="text-center">开户银行</th>
          <th class="text-center">银行账号</th>
          <th class="text-center">经手人</th>
          <th class="text-center">操作</th>

        </tr>
        </thead>
        <tbody>
        <% @cards.each do |card| %>
            <tr>
              <td><%= card.name %></td>
              <td><%= card.bankdeposit %></td>
              <td><%= card.bankaccount %></td>
              <td><%= card.operator %></td>

              <td><%= link_to '编辑',edit_user_card_path(@user,card) %>
                    <%= link_to '删除', [@user,card], method: :delete, data: { confirm: '确认删除?' } %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="text-right">
        <%= link_to "新增卡",new_user_card_path(@user),class: "btn btn-w-m btn-primary" %>&nbsp;
        <%= link_to "返回",user_path(@user),class: "btn btn-w-m btn-primary" %>
      </div>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/cards/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增银行卡</h3>
    </div>
    <%= render 'form', card: @card %>
  </div>
</div>
<%=render 'layerend' %>